// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upvote.proto

package pb_upvote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUpvote struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Vote                 string   `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUpvote) Reset()         { *m = NewUpvote{} }
func (m *NewUpvote) String() string { return proto.CompactTextString(m) }
func (*NewUpvote) ProtoMessage()    {}
func (*NewUpvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{0}
}

func (m *NewUpvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUpvote.Unmarshal(m, b)
}
func (m *NewUpvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUpvote.Marshal(b, m, deterministic)
}
func (m *NewUpvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUpvote.Merge(m, src)
}
func (m *NewUpvote) XXX_Size() int {
	return xxx_messageInfo_NewUpvote.Size(m)
}
func (m *NewUpvote) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUpvote.DiscardUnknown(m)
}

var xxx_messageInfo_NewUpvote proto.InternalMessageInfo

func (m *NewUpvote) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *NewUpvote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewUpvote) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *NewUpvote) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Upvote struct {
	UpvoteId             string   `protobuf:"bytes,1,opt,name=upvoteId,proto3" json:"upvoteId,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Vote                 string   `protobuf:"bytes,4,opt,name=vote,proto3" json:"vote,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Upvote) Reset()         { *m = Upvote{} }
func (m *Upvote) String() string { return proto.CompactTextString(m) }
func (*Upvote) ProtoMessage()    {}
func (*Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{1}
}

func (m *Upvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upvote.Unmarshal(m, b)
}
func (m *Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upvote.Marshal(b, m, deterministic)
}
func (m *Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvote.Merge(m, src)
}
func (m *Upvote) XXX_Size() int {
	return xxx_messageInfo_Upvote.Size(m)
}
func (m *Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_Upvote proto.InternalMessageInfo

func (m *Upvote) GetUpvoteId() string {
	if m != nil {
		return m.UpvoteId
	}
	return ""
}

func (m *Upvote) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Upvote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Upvote) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *Upvote) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUpvote)(nil), "NewUpvote")
	proto.RegisterType((*Upvote)(nil), "Upvote")
}

func init() { proto.RegisterFile("proto/upvote.proto", fileDescriptor_e0cbadb649e4b3f0) }

var fileDescriptor_e0cbadb649e4b3f0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x28, 0xcb, 0x2f, 0x49, 0xd5, 0x03, 0x73, 0x94, 0xf2, 0xb9, 0x38, 0xfd,
	0x52, 0xcb, 0x43, 0xc1, 0x42, 0x42, 0x32, 0x5c, 0x9c, 0xc5, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9,
	0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21, 0x31, 0x2e, 0xb6, 0xd2,
	0xe2, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x26, 0xb0, 0x14, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x02, 0xd2,
	0x2d, 0xc1, 0x0c, 0x16, 0x05, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0x73, 0x73, 0x53, 0xf3,
	0x4a, 0x24, 0x58, 0xc0, 0xc2, 0x30, 0xae, 0x52, 0x07, 0x23, 0x17, 0x1b, 0xd4, 0x3a, 0x29, 0x2e,
	0x0e, 0x88, 0x5b, 0xe0, 0xb6, 0xc1, 0xf9, 0xa8, 0x4e, 0x61, 0xc2, 0xed, 0x14, 0x66, 0xac, 0x4e,
	0x61, 0xc1, 0xee, 0x14, 0x56, 0x14, 0xa7, 0x18, 0x19, 0x70, 0xf1, 0x42, 0x5c, 0x12, 0x0c, 0x31,
	0x58, 0x48, 0x9e, 0x8b, 0xcd, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x55, 0x88, 0x4b, 0x0f, 0x1e, 0x2a,
	0x52, 0xec, 0x7a, 0x10, 0x86, 0x12, 0x83, 0x93, 0x58, 0x94, 0x88, 0x7e, 0x41, 0x12, 0x34, 0x04,
	0xad, 0x0b, 0x92, 0xe2, 0x21, 0xac, 0x24, 0x36, 0x70, 0x60, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x3b, 0x82, 0x16, 0x62, 0x01, 0x00, 0x00,
}
