// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/upvote.proto

package pb_upvote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUpvote struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Vote                 string   `protobuf:"bytes,3,opt,name=vote,proto3" json:"vote,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUpvote) Reset()         { *m = NewUpvote{} }
func (m *NewUpvote) String() string { return proto.CompactTextString(m) }
func (*NewUpvote) ProtoMessage()    {}
func (*NewUpvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{0}
}

func (m *NewUpvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUpvote.Unmarshal(m, b)
}
func (m *NewUpvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUpvote.Marshal(b, m, deterministic)
}
func (m *NewUpvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUpvote.Merge(m, src)
}
func (m *NewUpvote) XXX_Size() int {
	return xxx_messageInfo_NewUpvote.Size(m)
}
func (m *NewUpvote) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUpvote.DiscardUnknown(m)
}

var xxx_messageInfo_NewUpvote proto.InternalMessageInfo

func (m *NewUpvote) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *NewUpvote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NewUpvote) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *NewUpvote) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Upvote struct {
	UpvoteId             string   `protobuf:"bytes,1,opt,name=upvoteId,proto3" json:"upvoteId,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Vote                 string   `protobuf:"bytes,4,opt,name=vote,proto3" json:"vote,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Upvote) Reset()         { *m = Upvote{} }
func (m *Upvote) String() string { return proto.CompactTextString(m) }
func (*Upvote) ProtoMessage()    {}
func (*Upvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{1}
}

func (m *Upvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upvote.Unmarshal(m, b)
}
func (m *Upvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upvote.Marshal(b, m, deterministic)
}
func (m *Upvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvote.Merge(m, src)
}
func (m *Upvote) XXX_Size() int {
	return xxx_messageInfo_Upvote.Size(m)
}
func (m *Upvote) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvote.DiscardUnknown(m)
}

var xxx_messageInfo_Upvote proto.InternalMessageInfo

func (m *Upvote) GetUpvoteId() string {
	if m != nil {
		return m.UpvoteId
	}
	return ""
}

func (m *Upvote) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Upvote) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Upvote) GetVote() string {
	if m != nil {
		return m.Vote
	}
	return ""
}

func (m *Upvote) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type FilterUpvote struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterUpvote) Reset()         { *m = FilterUpvote{} }
func (m *FilterUpvote) String() string { return proto.CompactTextString(m) }
func (*FilterUpvote) ProtoMessage()    {}
func (*FilterUpvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{2}
}

func (m *FilterUpvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterUpvote.Unmarshal(m, b)
}
func (m *FilterUpvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterUpvote.Marshal(b, m, deterministic)
}
func (m *FilterUpvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterUpvote.Merge(m, src)
}
func (m *FilterUpvote) XXX_Size() int {
	return xxx_messageInfo_FilterUpvote.Size(m)
}
func (m *FilterUpvote) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterUpvote.DiscardUnknown(m)
}

var xxx_messageInfo_FilterUpvote proto.InternalMessageInfo

func (m *FilterUpvote) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Upvotes struct {
	Upvotes              []*Upvote `protobuf:"bytes,1,rep,name=upvotes,proto3" json:"upvotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Upvotes) Reset()         { *m = Upvotes{} }
func (m *Upvotes) String() string { return proto.CompactTextString(m) }
func (*Upvotes) ProtoMessage()    {}
func (*Upvotes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{3}
}

func (m *Upvotes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upvotes.Unmarshal(m, b)
}
func (m *Upvotes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upvotes.Marshal(b, m, deterministic)
}
func (m *Upvotes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upvotes.Merge(m, src)
}
func (m *Upvotes) XXX_Size() int {
	return xxx_messageInfo_Upvotes.Size(m)
}
func (m *Upvotes) XXX_DiscardUnknown() {
	xxx_messageInfo_Upvotes.DiscardUnknown(m)
}

var xxx_messageInfo_Upvotes proto.InternalMessageInfo

func (m *Upvotes) GetUpvotes() []*Upvote {
	if m != nil {
		return m.Upvotes
	}
	return nil
}

type UpvoteId struct {
	UpvoteId             string   `protobuf:"bytes,1,opt,name=upvoteId,proto3" json:"upvoteId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpvoteId) Reset()         { *m = UpvoteId{} }
func (m *UpvoteId) String() string { return proto.CompactTextString(m) }
func (*UpvoteId) ProtoMessage()    {}
func (*UpvoteId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{4}
}

func (m *UpvoteId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpvoteId.Unmarshal(m, b)
}
func (m *UpvoteId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpvoteId.Marshal(b, m, deterministic)
}
func (m *UpvoteId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpvoteId.Merge(m, src)
}
func (m *UpvoteId) XXX_Size() int {
	return xxx_messageInfo_UpvoteId.Size(m)
}
func (m *UpvoteId) XXX_DiscardUnknown() {
	xxx_messageInfo_UpvoteId.DiscardUnknown(m)
}

var xxx_messageInfo_UpvoteId proto.InternalMessageInfo

func (m *UpvoteId) GetUpvoteId() string {
	if m != nil {
		return m.UpvoteId
	}
	return ""
}

type EmptyUpvote struct {
	Return               bool     `protobuf:"varint,1,opt,name=return,proto3" json:"return,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyUpvote) Reset()         { *m = EmptyUpvote{} }
func (m *EmptyUpvote) String() string { return proto.CompactTextString(m) }
func (*EmptyUpvote) ProtoMessage()    {}
func (*EmptyUpvote) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{5}
}

func (m *EmptyUpvote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyUpvote.Unmarshal(m, b)
}
func (m *EmptyUpvote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyUpvote.Marshal(b, m, deterministic)
}
func (m *EmptyUpvote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyUpvote.Merge(m, src)
}
func (m *EmptyUpvote) XXX_Size() int {
	return xxx_messageInfo_EmptyUpvote.Size(m)
}
func (m *EmptyUpvote) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyUpvote.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyUpvote proto.InternalMessageInfo

func (m *EmptyUpvote) GetReturn() bool {
	if m != nil {
		return m.Return
	}
	return false
}

type ServiceId struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceId) Reset()         { *m = ServiceId{} }
func (m *ServiceId) String() string { return proto.CompactTextString(m) }
func (*ServiceId) ProtoMessage()    {}
func (*ServiceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{6}
}

func (m *ServiceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceId.Unmarshal(m, b)
}
func (m *ServiceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceId.Marshal(b, m, deterministic)
}
func (m *ServiceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceId.Merge(m, src)
}
func (m *ServiceId) XXX_Size() int {
	return xxx_messageInfo_ServiceId.Size(m)
}
func (m *ServiceId) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceId.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceId proto.InternalMessageInfo

func (m *ServiceId) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

type ScoreResponse struct {
	Upvotes              int32    `protobuf:"varint,1,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	Downvotes            int32    `protobuf:"varint,2,opt,name=downvotes,proto3" json:"downvotes,omitempty"`
	Score                int32    `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreResponse) Reset()         { *m = ScoreResponse{} }
func (m *ScoreResponse) String() string { return proto.CompactTextString(m) }
func (*ScoreResponse) ProtoMessage()    {}
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0cbadb649e4b3f0, []int{7}
}

func (m *ScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreResponse.Unmarshal(m, b)
}
func (m *ScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreResponse.Marshal(b, m, deterministic)
}
func (m *ScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreResponse.Merge(m, src)
}
func (m *ScoreResponse) XXX_Size() int {
	return xxx_messageInfo_ScoreResponse.Size(m)
}
func (m *ScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreResponse proto.InternalMessageInfo

func (m *ScoreResponse) GetUpvotes() int32 {
	if m != nil {
		return m.Upvotes
	}
	return 0
}

func (m *ScoreResponse) GetDownvotes() int32 {
	if m != nil {
		return m.Downvotes
	}
	return 0
}

func (m *ScoreResponse) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*NewUpvote)(nil), "NewUpvote")
	proto.RegisterType((*Upvote)(nil), "Upvote")
	proto.RegisterType((*FilterUpvote)(nil), "FilterUpvote")
	proto.RegisterType((*Upvotes)(nil), "Upvotes")
	proto.RegisterType((*UpvoteId)(nil), "UpvoteId")
	proto.RegisterType((*EmptyUpvote)(nil), "EmptyUpvote")
	proto.RegisterType((*ServiceId)(nil), "ServiceId")
	proto.RegisterType((*ScoreResponse)(nil), "ScoreResponse")
}

func init() { proto.RegisterFile("proto/upvote.proto", fileDescriptor_e0cbadb649e4b3f0) }

var fileDescriptor_e0cbadb649e4b3f0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xc7, 0x25, 0x5b, 0x9f, 0x93, 0xb8, 0x87, 0x21, 0x18, 0x21, 0x0a, 0x75, 0xb6, 0xa4, 0xb8,
	0x50, 0x36, 0x90, 0x1e, 0x7b, 0x4b, 0x3f, 0xc0, 0x97, 0x1e, 0x14, 0x7c, 0x29, 0x94, 0x12, 0x5b,
	0x73, 0x08, 0xc4, 0xda, 0x65, 0x77, 0x1d, 0xe3, 0x37, 0xe8, 0x83, 0xf6, 0x41, 0x8a, 0x76, 0x57,
	0xb2, 0x55, 0x5c, 0xdf, 0x66, 0xfe, 0x33, 0x9e, 0xf9, 0xcd, 0xdf, 0x5a, 0x40, 0xa9, 0x84, 0x11,
	0xb7, 0x5b, 0xf9, 0x22, 0x0c, 0x71, 0x9b, 0x30, 0x01, 0xf9, 0x77, 0xda, 0x2d, 0xad, 0x84, 0xaf,
	0x21, 0xd7, 0xa4, 0x5e, 0x9e, 0xd6, 0xb4, 0xa8, 0x8b, 0x70, 0x16, 0xce, 0xf3, 0xea, 0x20, 0xe0,
	0x14, 0x92, 0xad, 0x26, 0xb5, 0xa8, 0x8b, 0x91, 0x2d, 0xf9, 0x0c, 0x11, 0xa2, 0xf6, 0xd7, 0xc5,
	0xd8, 0xaa, 0x36, 0xc6, 0x02, 0xd2, 0xb5, 0xd8, 0x6c, 0xa8, 0x31, 0x45, 0x64, 0xe5, 0x2e, 0x65,
	0xbf, 0x43, 0x48, 0xfc, 0xba, 0x12, 0x32, 0xc7, 0xd2, 0x6f, 0xeb, 0xf3, 0x21, 0xca, 0xe8, 0xff,
	0x28, 0xe3, 0x93, 0x28, 0xd1, 0x69, 0x94, 0x78, 0x88, 0xc2, 0xe0, 0xf2, 0xdb, 0xd3, 0xb3, 0x21,
	0xe5, 0x79, 0x10, 0x22, 0xb3, 0x97, 0xe4, 0x59, 0x6c, 0xcc, 0x3e, 0x40, 0xea, 0xaa, 0x1a, 0xaf,
	0x21, 0x75, 0x78, 0xba, 0x08, 0x67, 0xe3, 0xf9, 0xc5, 0x5d, 0xca, 0x5d, 0xa9, 0xea, 0x74, 0xf6,
	0x0e, 0xb2, 0x65, 0x77, 0xc1, 0x99, 0xeb, 0xd8, 0x0d, 0x5c, 0x7c, 0xdd, 0x48, 0xb3, 0xf7, 0x8b,
	0xa7, 0x90, 0x28, 0x32, 0x5b, 0xd5, 0xd8, 0xc6, 0xac, 0xf2, 0x19, 0x7b, 0x0f, 0xf9, 0x43, 0x7f,
	0xf3, 0xd9, 0x3f, 0x87, 0xfd, 0x84, 0xc9, 0xc3, 0x5a, 0x28, 0xaa, 0x48, 0x4b, 0xd1, 0x68, 0x7b,
	0xf6, 0x81, 0x36, 0x9c, 0xc7, 0x3d, 0x64, 0x3b, 0xa8, 0x16, 0xbb, 0xc6, 0xd5, 0x46, 0xb6, 0x76,
	0x10, 0xf0, 0x0a, 0x62, 0xdd, 0x0e, 0xb2, 0xce, 0xc6, 0x95, 0x4b, 0xee, 0xfe, 0x84, 0x30, 0x71,
	0xb0, 0x1e, 0x08, 0xdf, 0x40, 0xf2, 0x59, 0xd1, 0xa3, 0x21, 0x04, 0xde, 0x7f, 0x41, 0x65, 0x67,
	0x09, 0x0b, 0xf0, 0x1a, 0xa2, 0x8a, 0x1e, 0x6b, 0x9c, 0xf0, 0x63, 0x93, 0xcb, 0xcc, 0x77, 0x68,
	0x16, 0xe0, 0x0c, 0xb2, 0xb6, 0xe5, 0x7e, 0xbf, 0xa8, 0x31, 0xe7, 0x9d, 0x73, 0xc3, 0x21, 0xc9,
	0x52, 0xd6, 0xed, 0x96, 0x4e, 0x2c, 0x2f, 0xf9, 0x91, 0x75, 0x2c, 0xc0, 0xb7, 0x90, 0x7c, 0xa1,
	0x67, 0x32, 0x74, 0x3c, 0xe2, 0xdf, 0xa6, 0x1b, 0x88, 0xad, 0x3d, 0x08, 0xbc, 0x77, 0xb4, 0x7c,
	0xc5, 0x07, 0x96, 0xb1, 0xe0, 0x7e, 0xfa, 0xe3, 0xea, 0x56, 0xae, 0xfc, 0x0b, 0xf9, 0x24, 0x57,
	0xbf, 0x5c, 0xb4, 0x4a, 0xec, 0x63, 0xf9, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x83, 0xa4, 0xa5,
	0x2a, 0x42, 0x03, 0x00, 0x00,
}
