// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gRPC/proto/users.proto

package backend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUser) Reset()         { *m = NewUser{} }
func (m *NewUser) String() string { return proto.CompactTextString(m) }
func (*NewUser) ProtoMessage()    {}
func (*NewUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{0}
}

func (m *NewUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUser.Unmarshal(m, b)
}
func (m *NewUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUser.Marshal(b, m, deterministic)
}
func (m *NewUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUser.Merge(m, src)
}
func (m *NewUser) XXX_Size() int {
	return xxx_messageInfo_NewUser.Size(m)
}
func (m *NewUser) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUser.DiscardUnknown(m)
}

var xxx_messageInfo_NewUser proto.InternalMessageInfo

func (m *NewUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NewUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type FilterName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterName) Reset()         { *m = FilterName{} }
func (m *FilterName) String() string { return proto.CompactTextString(m) }
func (*FilterName) ProtoMessage()    {}
func (*FilterName) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{2}
}

func (m *FilterName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterName.Unmarshal(m, b)
}
func (m *FilterName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterName.Marshal(b, m, deterministic)
}
func (m *FilterName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterName.Merge(m, src)
}
func (m *FilterName) XXX_Size() int {
	return xxx_messageInfo_FilterName.Size(m)
}
func (m *FilterName) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterName.DiscardUnknown(m)
}

var xxx_messageInfo_FilterName proto.InternalMessageInfo

func (m *FilterName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{3}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserId struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{4}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateUserInfo struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfo) Reset()         { *m = UpdateUserInfo{} }
func (m *UpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfo) ProtoMessage()    {}
func (*UpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{5}
}

func (m *UpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfo.Unmarshal(m, b)
}
func (m *UpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfo.Merge(m, src)
}
func (m *UpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfo.Size(m)
}
func (m *UpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfo proto.InternalMessageInfo

func (m *UpdateUserInfo) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_22afd743b9ca908a, []int{7}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUser)(nil), "proto.NewUser")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*FilterName)(nil), "proto.FilterName")
	proto.RegisterType((*Users)(nil), "proto.Users")
	proto.RegisterType((*UserId)(nil), "proto.userId")
	proto.RegisterType((*UpdateUserInfo)(nil), "proto.UpdateUserInfo")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*Token)(nil), "proto.Token")
}

func init() { proto.RegisterFile("gRPC/proto/users.proto", fileDescriptor_22afd743b9ca908a) }

var fileDescriptor_22afd743b9ca908a = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x4b, 0x4f, 0xea, 0x50,
	0x10, 0xc7, 0x69, 0x69, 0x7b, 0xb9, 0xc3, 0x23, 0xb9, 0x73, 0x95, 0x34, 0x4d, 0x4c, 0xea, 0xd9,
	0x88, 0xc6, 0x80, 0xc1, 0xa5, 0x1b, 0x03, 0xc6, 0x84, 0xc4, 0xa0, 0xa9, 0xb2, 0x71, 0x57, 0xe8,
	0x48, 0x1a, 0xa0, 0xc5, 0x9e, 0x83, 0xc4, 0x0f, 0xe2, 0xf7, 0x35, 0xe7, 0xb4, 0xbc, 0x2a, 0xac,
	0x5c, 0x75, 0xe6, 0xfc, 0xe7, 0xf1, 0x9f, 0x5f, 0xa1, 0x3e, 0xf6, 0x9e, 0xba, 0xad, 0x79, 0x12,
	0x8b, 0xb8, 0xb5, 0xe0, 0x94, 0xf0, 0xa6, 0x8a, 0xd1, 0x54, 0x1f, 0xf6, 0x08, 0x7f, 0xfa, 0xb4,
	0x1c, 0x70, 0x4a, 0x10, 0xc1, 0x88, 0xfc, 0x19, 0xd9, 0x9a, 0xab, 0x35, 0xfe, 0x7a, 0x2a, 0xc6,
	0x23, 0x30, 0x69, 0xe6, 0x87, 0x53, 0x5b, 0x57, 0x8f, 0x69, 0x82, 0x0e, 0x94, 0xe6, 0x3e, 0xe7,
	0xcb, 0x38, 0x09, 0xec, 0xa2, 0x12, 0xd6, 0x39, 0x0b, 0xc0, 0x50, 0xd3, 0xea, 0x60, 0xc9, 0x75,
	0xbd, 0x40, 0xcd, 0xab, 0x7a, 0x59, 0xb6, 0xde, 0xa2, 0xef, 0xdb, 0x52, 0x3c, 0xb4, 0xc5, 0xc8,
	0x6d, 0x71, 0x01, 0xee, 0xc3, 0xa9, 0xa0, 0xa4, 0x2f, 0xfb, 0xf7, 0x38, 0x67, 0x17, 0x60, 0x4a,
	0x1f, 0x1c, 0x4f, 0xc1, 0x54, 0x77, 0xdb, 0x9a, 0x5b, 0x6c, 0x94, 0xdb, 0xe5, 0xf4, 0xfe, 0xa6,
	0x14, 0xbd, 0x54, 0x61, 0xee, 0xca, 0xeb, 0x21, 0xd7, 0xcc, 0x83, 0xda, 0x60, 0x1e, 0xf8, 0x82,
	0x64, 0x5b, 0x2f, 0x7a, 0x8b, 0x7f, 0x7f, 0x1f, 0xbb, 0x85, 0xca, 0x43, 0x3c, 0x0e, 0x23, 0x8f,
	0xde, 0x17, 0xc4, 0xc5, 0xa6, 0x4a, 0x3b, 0x44, 0x41, 0xcf, 0x51, 0x38, 0x01, 0xf3, 0x25, 0x9e,
	0x50, 0x24, 0x5b, 0x85, 0x0c, 0x56, 0xad, 0x2a, 0x69, 0x7f, 0xe9, 0x50, 0x96, 0x7e, 0x9f, 0x29,
	0xf9, 0x08, 0x47, 0x84, 0x67, 0x60, 0x75, 0x13, 0xf2, 0x05, 0x61, 0x2d, 0x83, 0x90, 0xfd, 0x7a,
	0x67, 0x1b, 0x0a, 0x2b, 0xe0, 0x39, 0x18, 0x1e, 0xf9, 0x01, 0xfe, 0xcb, 0x9e, 0x37, 0xa8, 0x9d,
	0xca, 0x56, 0x25, 0x67, 0x05, 0x6c, 0x40, 0x49, 0x96, 0x76, 0x3e, 0x7b, 0x01, 0x56, 0x33, 0x2d,
	0x25, 0x91, 0x1f, 0x7a, 0x05, 0x56, 0x8a, 0x10, 0x8f, 0x57, 0xc2, 0x0e, 0x51, 0x67, 0xb7, 0x5d,
	0xcd, 0xb6, 0xee, 0x68, 0x4a, 0x82, 0xf2, 0x93, 0x7f, 0x54, 0x5e, 0x82, 0xa9, 0x50, 0xe2, 0xff,
	0x4c, 0xd9, 0x06, 0xbb, 0xf6, 0xac, 0x58, 0xb1, 0x42, 0xa7, 0xf2, 0x0a, 0xcd, 0xd6, 0xcd, 0xd0,
	0x1f, 0x4d, 0x28, 0x0a, 0x86, 0x96, 0x12, 0xaf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x70,
	0xcc, 0x26, 0x29, 0x03, 0x00, 0x00,
}
