// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package pb_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Site                 string   `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewService) Reset()         { *m = NewService{} }
func (m *NewService) String() string { return proto.CompactTextString(m) }
func (*NewService) ProtoMessage()    {}
func (*NewService) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{0}
}

func (m *NewService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewService.Unmarshal(m, b)
}
func (m *NewService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewService.Marshal(b, m, deterministic)
}
func (m *NewService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewService.Merge(m, src)
}
func (m *NewService) XXX_Size() int {
	return xxx_messageInfo_NewService.Size(m)
}
func (m *NewService) XXX_DiscardUnknown() {
	xxx_messageInfo_NewService.DiscardUnknown(m)
}

var xxx_messageInfo_NewService proto.InternalMessageInfo

func (m *NewService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewService) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type Service struct {
	ServiceId            string   `protobuf:"bytes,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type FilterService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterService) Reset()         { *m = FilterService{} }
func (m *FilterService) String() string { return proto.CompactTextString(m) }
func (*FilterService) ProtoMessage()    {}
func (*FilterService) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{2}
}

func (m *FilterService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterService.Unmarshal(m, b)
}
func (m *FilterService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterService.Marshal(b, m, deterministic)
}
func (m *FilterService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterService.Merge(m, src)
}
func (m *FilterService) XXX_Size() int {
	return xxx_messageInfo_FilterService.Size(m)
}
func (m *FilterService) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterService.DiscardUnknown(m)
}

var xxx_messageInfo_FilterService proto.InternalMessageInfo

func (m *FilterService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Services struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Services) Reset()         { *m = Services{} }
func (m *Services) String() string { return proto.CompactTextString(m) }
func (*Services) ProtoMessage()    {}
func (*Services) Descriptor() ([]byte, []int) {
	return fileDescriptor_c33392ef2c1961ba, []int{3}
}

func (m *Services) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Services.Unmarshal(m, b)
}
func (m *Services) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Services.Marshal(b, m, deterministic)
}
func (m *Services) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Services.Merge(m, src)
}
func (m *Services) XXX_Size() int {
	return xxx_messageInfo_Services.Size(m)
}
func (m *Services) XXX_DiscardUnknown() {
	xxx_messageInfo_Services.DiscardUnknown(m)
}

var xxx_messageInfo_Services proto.InternalMessageInfo

func (m *Services) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*NewService)(nil), "NewService")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*FilterService)(nil), "FilterService")
	proto.RegisterType((*Services)(nil), "Services")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_c33392ef2c1961ba) }

var fileDescriptor_c33392ef2c1961ba = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x94, 0x4c, 0xb8, 0xb8,
	0xfc, 0x52, 0xcb, 0x83, 0x21, 0x62, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xac, 0x38, 0xb3, 0x24, 0x55, 0x82, 0x09, 0x22,
	0x06, 0x62, 0x2b, 0xf9, 0x73, 0xb1, 0xc3, 0xb4, 0xc8, 0x70, 0x71, 0x42, 0x4d, 0xf4, 0x4c, 0x81,
	0xea, 0x43, 0x08, 0xc0, 0x0d, 0x64, 0xc2, 0x62, 0x20, 0x33, 0x92, 0x81, 0xca, 0x5c, 0xbc, 0x6e,
	0x99, 0x39, 0x25, 0xa9, 0x45, 0x78, 0x5c, 0xa2, 0x64, 0xc0, 0xc5, 0x01, 0x95, 0x2e, 0x16, 0x52,
	0xe1, 0xe2, 0x80, 0xda, 0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa1, 0x07, 0x95,
	0x0c, 0x82, 0xcb, 0x18, 0x45, 0x70, 0xf1, 0x41, 0x05, 0x61, 0xe6, 0x2a, 0x72, 0xb1, 0x39, 0x17,
	0xa5, 0x26, 0x96, 0xa4, 0x0a, 0x71, 0xeb, 0x21, 0x3c, 0x2e, 0x05, 0xd7, 0xac, 0xc4, 0x20, 0xa4,
	0xcc, 0xc5, 0x12, 0x94, 0x9a, 0x98, 0x22, 0xc4, 0xa7, 0x87, 0xe2, 0x24, 0x29, 0x4e, 0x98, 0x9a,
	0x62, 0x25, 0x06, 0x27, 0x89, 0x28, 0x31, 0xfd, 0x82, 0x24, 0x58, 0x60, 0x5a, 0x17, 0x24, 0xc5,
	0x43, 0x99, 0x49, 0x6c, 0xe0, 0x80, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x29, 0x10, 0x2e,
	0x81, 0x6f, 0x01, 0x00, 0x00,
}
