// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gRPC/proto/services.proto

package backend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Site                 string   `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewService) Reset()         { *m = NewService{} }
func (m *NewService) String() string { return proto.CompactTextString(m) }
func (*NewService) ProtoMessage()    {}
func (*NewService) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{0}
}

func (m *NewService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewService.Unmarshal(m, b)
}
func (m *NewService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewService.Marshal(b, m, deterministic)
}
func (m *NewService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewService.Merge(m, src)
}
func (m *NewService) XXX_Size() int {
	return xxx_messageInfo_NewService.Size(m)
}
func (m *NewService) XXX_DiscardUnknown() {
	xxx_messageInfo_NewService.DiscardUnknown(m)
}

var xxx_messageInfo_NewService proto.InternalMessageInfo

func (m *NewService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewService) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type Service struct {
	ServiceId            uint32   `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Site                 string   `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type FilterName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterName) Reset()         { *m = FilterName{} }
func (m *FilterName) String() string { return proto.CompactTextString(m) }
func (*FilterName) ProtoMessage()    {}
func (*FilterName) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{2}
}

func (m *FilterName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterName.Unmarshal(m, b)
}
func (m *FilterName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterName.Marshal(b, m, deterministic)
}
func (m *FilterName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterName.Merge(m, src)
}
func (m *FilterName) XXX_Size() int {
	return xxx_messageInfo_FilterName.Size(m)
}
func (m *FilterName) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterName.DiscardUnknown(m)
}

var xxx_messageInfo_FilterName proto.InternalMessageInfo

func (m *FilterName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Services struct {
	Service              []*Service `protobuf:"bytes,1,rep,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Services) Reset()         { *m = Services{} }
func (m *Services) String() string { return proto.CompactTextString(m) }
func (*Services) ProtoMessage()    {}
func (*Services) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{3}
}

func (m *Services) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Services.Unmarshal(m, b)
}
func (m *Services) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Services.Marshal(b, m, deterministic)
}
func (m *Services) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Services.Merge(m, src)
}
func (m *Services) XXX_Size() int {
	return xxx_messageInfo_Services.Size(m)
}
func (m *Services) XXX_DiscardUnknown() {
	xxx_messageInfo_Services.DiscardUnknown(m)
}

var xxx_messageInfo_Services proto.InternalMessageInfo

func (m *Services) GetService() []*Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type ServiceId struct {
	ServiceId            uint32   `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceId) Reset()         { *m = ServiceId{} }
func (m *ServiceId) String() string { return proto.CompactTextString(m) }
func (*ServiceId) ProtoMessage()    {}
func (*ServiceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{4}
}

func (m *ServiceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceId.Unmarshal(m, b)
}
func (m *ServiceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceId.Marshal(b, m, deterministic)
}
func (m *ServiceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceId.Merge(m, src)
}
func (m *ServiceId) XXX_Size() int {
	return xxx_messageInfo_ServiceId.Size(m)
}
func (m *ServiceId) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceId.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceId proto.InternalMessageInfo

func (m *ServiceId) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

type UpdateService struct {
	ServiceId            uint32   `protobuf:"varint,1,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateService) Reset()         { *m = UpdateService{} }
func (m *UpdateService) String() string { return proto.CompactTextString(m) }
func (*UpdateService) ProtoMessage()    {}
func (*UpdateService) Descriptor() ([]byte, []int) {
	return fileDescriptor_78a41022e10ab118, []int{5}
}

func (m *UpdateService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateService.Unmarshal(m, b)
}
func (m *UpdateService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateService.Marshal(b, m, deterministic)
}
func (m *UpdateService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateService.Merge(m, src)
}
func (m *UpdateService) XXX_Size() int {
	return xxx_messageInfo_UpdateService.Size(m)
}
func (m *UpdateService) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateService.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateService proto.InternalMessageInfo

func (m *UpdateService) GetServiceId() uint32 {
	if m != nil {
		return m.ServiceId
	}
	return 0
}

func (m *UpdateService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateService) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*NewService)(nil), "proto.NewService")
	proto.RegisterType((*Service)(nil), "proto.Service")
	proto.RegisterType((*FilterName)(nil), "proto.FilterName")
	proto.RegisterType((*Services)(nil), "proto.Services")
	proto.RegisterType((*ServiceId)(nil), "proto.serviceId")
	proto.RegisterType((*UpdateService)(nil), "proto.UpdateService")
}

func init() { proto.RegisterFile("gRPC/proto/services.proto", fileDescriptor_78a41022e10ab118) }

var fileDescriptor_78a41022e10ab118 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xde, 0xba, 0xad, 0xdb, 0x9e, 0xce, 0x69, 0xd8, 0xa1, 0x16, 0x0f, 0x25, 0xa7, 0x0a, 0xda,
	0x42, 0xdd, 0xcd, 0xdb, 0x26, 0xc2, 0x2e, 0x53, 0x2a, 0x22, 0x78, 0xcb, 0x96, 0x87, 0x14, 0xbb,
	0x1f, 0x34, 0x41, 0xf1, 0xea, 0x5f, 0x2e, 0x4d, 0xd2, 0x76, 0x9b, 0xc5, 0x83, 0xa7, 0x26, 0xef,
	0xfb, 0xf2, 0xfd, 0x78, 0x85, 0xf3, 0xb7, 0xf8, 0x71, 0x1a, 0x6e, 0xb3, 0x8d, 0xdc, 0x84, 0x02,
	0xb3, 0x8f, 0x64, 0x89, 0x22, 0x50, 0x57, 0xd2, 0x51, 0x1f, 0x3a, 0x06, 0x98, 0xe3, 0xe7, 0x93,
	0xc6, 0x08, 0x81, 0xf6, 0x9a, 0xad, 0xd0, 0x69, 0x7a, 0x4d, 0xbf, 0x1f, 0xab, 0x73, 0x3e, 0x13,
	0x89, 0x44, 0xc7, 0xd2, 0xb3, 0xfc, 0x4c, 0x1f, 0xa0, 0x5b, 0x3c, 0xb9, 0x80, 0xbe, 0x51, 0x9e,
	0x71, 0xf5, 0x6e, 0x10, 0x57, 0x83, 0x52, 0xd0, 0xaa, 0x11, 0x6c, 0xed, 0x08, 0x7a, 0x00, 0xf7,
	0x49, 0x2a, 0x31, 0x9b, 0x1b, 0xc6, 0x61, 0x0c, 0x3a, 0x86, 0x9e, 0xb1, 0x14, 0xc4, 0x87, 0xae,
	0xb1, 0x70, 0x9a, 0x5e, 0xcb, 0x3f, 0x8a, 0x4e, 0x74, 0xa9, 0xc0, 0x30, 0xe2, 0x02, 0xa6, 0x97,
	0x3b, 0xe9, 0xfe, 0x8e, 0x4a, 0x5f, 0x60, 0xf0, 0xbc, 0xe5, 0x4c, 0xe2, 0xff, 0x9b, 0x8d, 0xa0,
	0x83, 0x2b, 0x96, 0xa4, 0xa6, 0x9a, 0xbe, 0x44, 0xdf, 0x16, 0x0c, 0x8b, 0xe8, 0x85, 0xf6, 0x35,
	0xd8, 0xd3, 0x0c, 0x99, 0x44, 0x72, 0x66, 0xa2, 0x57, 0x7f, 0xc1, 0x3d, 0x68, 0x43, 0x1b, 0xe4,
	0x0a, 0xda, 0x31, 0x32, 0x5e, 0x92, 0xab, 0x5d, 0xb9, 0xc3, 0x7d, 0xb2, 0xa0, 0x0d, 0x12, 0x40,
	0x2f, 0x67, 0x4f, 0xbe, 0x66, 0x9c, 0x9c, 0x1a, 0xb8, 0x0c, 0x5e, 0xa3, 0x1e, 0x81, 0xad, 0x9b,
	0x93, 0x91, 0xc1, 0xf6, 0x16, 0xe1, 0xfe, 0xd2, 0x50, 0x1e, 0xf6, 0x1d, 0xa6, 0x28, 0xb1, 0xc6,
	0xa1, 0x86, 0x3f, 0x39, 0x7e, 0x85, 0x20, 0xbc, 0x5d, 0xb0, 0xe5, 0x3b, 0xae, 0xf9, 0xc2, 0x56,
	0x84, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x41, 0x35, 0xa3, 0xa0, 0x02, 0x00, 0x00,
}
